version: '3.7'
networks:
  laravelnetwork:
    driver: bridge
services: 
  db:
    container_name: dbmysql
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      -  /var/www/html/vendor/
    environment:
      - MYSQL_DATABASE=laravel-realworld
      - MYSQL_USER=password
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - laravelnetwork
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
    networks:
      - laravelnetwork
  app:
    container_name: laravelapp
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      -  /var/www/html/vendor/
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_PORT:-8080}:8080
    working_dir: /var/www/html
    networks:
      - laravelnetwork
  